#!/bin/bash

# vim
alias v="vim"

# git
alias g="git"

# List files and directories.
alias l='ls -G'
alias ls='ls -G'
alias ll='ls -la'
alias tree="ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'"

alias grep='grep --color=auto'

# Copy output of last command to clipboard.
alias clip="fc -e -|pbcopy"
