#!/bin/bash

setopt AUTO_CD

autoload -U colors && colors
autoload -U promptinit && promptinit
autoload -Uz vcs_info

precmd() {
    vcs_info
}

setopt prompt_subst

zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:*'    formats "%{$fg[blue]%} %m%u%c%{$reset_color%} %{$fg[red]%}%b%{$reset_color%}:%r"
zstyle ':vcs_info:*'    nvcsformats   ""
zstyle ':vcs_info:*'    actionformats '%F{5}(%f%s%F{5})%F{3}-%F{5}[%F{2}%b%F{3}|%F{1}%a%F{5}]%f '

PROMPT='%{$fg[green]%}%~> %{$reset_color%}%'
RPROMPT='${vcs_info_msg_0_}'

bindkey -e
bindkey ';5C' forward-word
bindkey ';5D' backward-word

eval "$(jump shell zsh)"
