#!/usr/bin/env bash

fetch() {
  sudo add-apt-repository "$1"
}

install() {
  sudo apt-get update
  sudo apt-get install "$1"
}

# Install application launcher
fetch ppa:nilarimogard/webupd8 && install albert

###
## Verion control systems
###

# Install git
fetch ppa:git-core/ppa && install git
install subversion

###
## Editor and terminal
###

install vim
install tmux

###
## Programming languages and environments
###

# Install Go environment
fetch ppa:ubuntu-lxc/lxd-stable && install golang

###
## Unix tools
###

# Install archiving utility
install pax

