#!/usr/bin/env bash

clone_git_repo () {
  cd "${HOME}"
  [ -d $2 ] || git clone $1 $2
}

ENVIRONMENT_DIR="$(cd "${0%/*}/.."; pwd)"

cd "${ENVIRONMENT_DIR}" && pax -wrs'/(.*)/.${BASH_REMATCH[1]}/' * "${HOME}"

# Link files and directories from HOME to ENVIRONMENT_DIR
for file in "$ENVIRONMENT_DIR"/*; do
  name="$(basename "$file")"
  dotname=".${name}"

  if ! [[ "setup" =~ $name ]]; then
    ln -sfnv ${file#$HOME/} "${HOME}/${dotname}"
  fi
done

# Install NeoBundle
clone_git_repo "https://github.com/Shougo/neobundle.vim.git" ".vim/bundle/neobundle.vim"
