#!/usr/bin/env zsh

# Install Homebrew unless it is already available.
which brew &> /dev/null || {
  ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)"
}

# Shell stuff.
brew install zsh
brew install tmux

# Core utilities.
brew install git mercurial
brew install coreutils
brew install lua
brew install ctags
brew install macvim --override-system-vim --with-lua
brew install cmake

# Language specific stuff.
brew install go
brew install rbenv ruby-build

# Extra utilities.
brew tap gsamokovarov/jump && brew install jump

brew update && brew upgrade
brew doctor
