#!/usr/bin/env zsh

# Install Homebrew unless it is already available.
which brew &> /dev/null || {
  ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)"
}

# Shell stuff.
brew install zsh

# Core utilities.
brew install git mercurial
brew install coreutils
brew install lua
brew install macvim --override-system-vim --with-lua

# Language specific stuff.
brew install go
brew install rbenv ruby-build

# Extra utilities.
brew tap gsamokovarov/jump && brew install jump

# Cask let you install Mac applications distributed as binaries.
brew tap phinze/homebrew-cask
brew install brew-cask

brew cask install alfred
brew cask install iterm2
brew cask install skype

brew update && brew upgrade
brew doctor
